Repository ponylang/crypto, pull requests merged in 2022-02, with the labels that each got.

#65 Add nodoc annotation to test code
  crypto/_test.pony
Labels: discuss during sync

#66 Support for using ponyup on Windows
  .release-notes/66.md
  make.ps1
Labels: changelog - added, discuss during sync

#67 Update to address PonyTest package being renamed
  .github/workflows/pr.yml
  .release-notes/ponytest.md
  crypto/_test.pony
Labels: changelog - fixed, discuss during sync

#68 Updates for libs build on Windows
  .release-notes/68.md
  README.md
  crypto/digest.pony
  make.ps1
Labels: changelog - fixed, discuss during sync

#69 Run PRs against release builds again
  .github/workflows/pr.yml
Labels: discuss during sync
