Repository ponylang/crypto, pull requests merged in 2023-01, with the labels that each got.

#79 Add documentation for selecting SSL library version
  README.md
Labels: discuss during sync

#78 Remove `md4` constructor from `Digest`
  .release-notes/remove-md4-digest.md
  crypto/_test.pony
  crypto/digest.pony
Labels: changelog - changed, discuss during sync

#80 Add OpenSSL 3 support
  .github/workflows/breakage-against-ponyc-latest.yml
  .github/workflows/pr.yml
  .release-notes/openssl3.md
  Makefile
  README.md
  crypto/_test.pony
  crypto/digest.pony
Labels: changelog - added, discuss during sync

#81 Update to LibreSSL 3.6.1 on Windows
  .release-notes/81.md
  make.ps1
Labels: changelog - changed, triggers release, discuss during sync
